[31m[1m14:53:20.95 <error> UnauthorizedError: no token detected in http header Authorization
    at Object.throw (F:\vue\myself-project\koa\server\node_modules\_koa@2.4.1@koa\lib\context.js:92:11)
    at module.exports (F:\vue\myself-project\koa\server\middleware\checkToken.js:32:12)
    at dispatch (F:\vue\myself-project\koa\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\vue\myself-project\koa\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\vue\myself-project\koa\server\node_modules\_koa-router@7.3.0@koa-router\lib\router.js:345:16
    at dispatch (F:\vue\myself-project\koa\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\vue\myself-project\koa\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
    at dispatch (F:\vue\myself-project\koa\server\node_modules\_koa-router@7.3.0@koa-router\lib\router.js:350:31)
    at dispatch (F:\vue\myself-project\koa\server\node_modules\_koa-compose@4.0.0@koa-compose\index.js:42:32)
    at next (F:\vue\myself-project\koa\server\node_modules\_koa-compose@4.0.0@koa-compose\index.js:43:18)
    at module.exports (F:\vue\myself-project\koa\server\middleware\initData.js:26:8)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) (in errorHandle.js:27)[22m[39m
[31m[1m16:59:47.84 <error> UnauthorizedError: expired token
    at Object.throw (F:\vue\myself-project\koa\server\node_modules\_koa@2.4.1@koa\lib\context.js:92:11)
    at module.exports (F:\vue\myself-project\koa\server\middleware\checkToken.js:28:13)
    at dispatch (F:\vue\myself-project\koa\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (F:\vue\myself-project\koa\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at F:\vue\myself-project\koa\server\node_modules\_koa-router@7.3.0@koa-router\lib\router.js:345:16
    at dispatch (F:\vue\myself-project\koa\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at F:\vue\myself-project\koa\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
    at dispatch (F:\vue\myself-project\koa\server\node_modules\_koa-router@7.3.0@koa-router\lib\router.js:350:31)
    at dispatch (F:\vue\myself-project\koa\server\node_modules\_koa-compose@4.0.0@koa-compose\index.js:42:32)
    at next (F:\vue\myself-project\koa\server\node_modules\_koa-compose@4.0.0@koa-compose\index.js:43:18)
    at module.exports (F:\vue\myself-project\koa\server\middleware\initData.js:27:8)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) (in errorHandle.js:27)[22m[39m
[31m[1m17:11:36.83 <error> InternalServerError: 服务器内部错误--存储初始化数据错误!
    at Object.throw (F:\vue\myself-project\koa\server\node_modules\_koa@2.4.1@koa\lib\context.js:92:11)
    at user.save.catch.err (F:\vue\myself-project\koa\server\middleware\initData.js:22:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) (in errorHandle.js:27)[22m[39m
[31m[1m17:11:41.87 <error> InternalServerError: 服务器内部错误--存储初始化数据错误!
    at Object.throw (F:\vue\myself-project\koa\server\node_modules\_koa@2.4.1@koa\lib\context.js:92:11)
    at user.save.catch.err (F:\vue\myself-project\koa\server\middleware\initData.js:22:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) (in errorHandle.js:27)[22m[39m
